### ISSUE TITLE
Datasource wot working via direct access "http://localhost:3333"

### ISSUE THREAD

**Issue by sean-fabri** [bergquist/fake-simple-json-datasource#1]
This is due to CORS issues, it may just be affecting my browser (chrome).

If you grant me push access I can send a Pull Request.

**Comment by bergquist** [comment]
@sean-fabri you can send pull requests without push access :)

**Comment by sean-fabri** [comment]
so I can :)

**Comment by bergquist** [comment]
Closed by #2
